version: '3'

services:
  srworking:
    image: srworking:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - D:\org\projects\fogbridge3\ActorModelDojo\src\SRworking\SRworking:/app
      - C:\Users\gracie\vsdbg:/remote_debugger:ro
      - C:\Users\gracie\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Users\gracie\.nuget\packages\:/root/.nuget/fallbackpackages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.0/SRworking.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
